# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxBaseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxBaseDemo
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources'

  target 'RxBaseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxBaseDemoUITests' do
    # Pods for testing
  end

end
